// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iznkrblrwyrhovgswqoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6bmtyYmxyd3lyaG92Z3N3cW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODEzNDIsImV4cCI6MjA2NTY1NzM0Mn0.clEfChs0Hl_BdDUOvnBmtw0_ictRuxZnK8MpFnrGYsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);